### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by TheLilStiles** [435vic/MinecraftMobControl#1] opened 2020-05-21 10:05 UTC
I wanna be able to control fish and rabbits and stuff.  There are many creatures that I cannot control and or are glitchy. Ex. Sheep. When I morph or try to control Sheep it instantly kills me. I cannot control fish or rabbits or some other things. And I do not know how to control a mob that is infront of me. do I left click it? with the compass? 

 A few more things, when I am close to a player, I would like to control a mob, but then it teleports me to a cave where the nearest mob is and its almost impossible to make it out to them. I know its a weird fix to do but I was wondering if you possibly have anything in mind to fix it.

Either way, great work on this plugin. This is by far the best mob control plugin that exists for 1.15.2  and I want to thank you for creating it. Have a good day, and I can only hope you keep updating this plugin.

**Comment by 435vic** [comment] 2020-05-21 19:51
Thank you very much! I've been working on that bug for quite a lot of of time, I thought it was fixed, but I guess not... I'll have a look and see if I can get it working. Thank you once again for your patience.

**Comment by 435vic** [comment] 2020-05-21 21:52
As for your other issues:
- You do have to right click the entity with the compass, I know it's a little unintuitive but I really want to keep as many options as possible in the hotbar and this is the only way I can do it.
- You can actually control fish and rabbits by right clicking them, it's just that I excluded them from the rest of the docile creatures on purpose so that it is easier for most players (Like if you wanted to follow a player across a shore and you end up as a fish on the ocean). 
- While it is intended functionality that you always possess the nearest mob/creature, regardless of it being underground or not, I do understand it might be better if you end up on the surface. However, I think that this is more of an intended mechanic than an unintended consequence of always choosing the nearest mob, because controlling a mob _already_ is quite an overpowered mechanic, so being forced to work with what mobs you already have can actualy make this whole thing a bit more balanced. As for escaping a cave, you can pretty much control the nearest docile mob and 90% of the time you will end up in the surface. If not, the enderman's flee always transports you to the highest block in a location, so you can also get to the surface that way. This brings us to my actual biggest priority, which is the bug you mentioned.

The issue is that once you control a docile mob, it is pretty much unpredictable what will happen next. Sometimes it kills, you, sometimes it doesn't. I'm pretty sure it has to do with the mob's maximum health, apparently the game doesn't like it when you meddle with the player's health. As it is pretty hard to test something that happens _randomly_, I'd like to ask you a favor: can you test this patched version? I capped the docile mobs' health to 6 hearts, which I think is reasonable for a harmless mob. Give it a try, and we'll go from there.

Once again, I thank you very much for your report.

The JAR file is in this archive:
[MobControl-1.0.1-DEV.zip](https://github.com/435vic/MinecraftMobControl/files/4665029/MobControl-1.0.1-DEV.zip)

**Comment by 435vic** [comment] 2020-08-23 23:38
As this issue has been officialy ghosted, I will close it. After a bunch of testing I can at least say that it will be far less common for this health issue to appear. If you have any further issues, make sure to file them individually. Thank you.

**Closed as completed by 435vic** 2020-08-23 23:38 UTC
Labels: bug
